ZRZ-1324 make seg true when session > 10sec + include two pageviews a…
managed-components/google-analytics-4 pull request #31
Opened 2024-05-31 09:59 UTC by ad-astra-via

2024-05-31 10:43 UTC, kuba-orlik commented on src/requestBuilder.ts
> +  if (typeof client !== 'undefined' && client) {
This check can be reduced to `if (client)` and the effect will remain unchanged, I believe

2024-06-05 14:18 UTC, jonnyparris requested changes

2024-06-05 14:18 UTC, jonnyparris commented on src/requestBuilder.ts
> +  }
```suggestion
  }
```
not needed

2024-06-05 14:18 UTC, jonnyparris commented on src/requestBuilder.ts
> +      engagementDuration > 10 &&
```suggestion
      engagementDuration >= 10 &&
```
Example in docs here https://support.google.com/analytics/answer/12195621?hl=en&ref_topic=11151952&sjid=11966088143636941671-EU suggests that it's 10 or more seconds

2024-06-10 14:04 UTC, merged